services:
  - type: web
    name: texting-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run migrate && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: texting
      - key: DB_PORT
        value: 18649
      - key: DB_SSL
        value: REQUIRED
      - key: DB_SSL_INSECURE
        value: "true"
      - key: DB_SSL_CA_PATH
        sync: false
      - key: SESSION_SECRET
        sync: false
